version: '3.8'

services:

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"    # HTTP for initial Certbot validation
      - "443:443"  # HTTPS for secure access
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro  # Custom NGINX config
      - ./nginx/ssl:/etc/letsencrypt  # Mount for Let's Encrypt certificates
      - uploads:/usr/share/nginx/html/files  # Serve files from uploads directory
    depends_on:
      - frontend
      - backend
    networks:
      - app-network

  frontend:
    image: oleksiipasichnyk/confl:null-client-2a77b51-20241118  # Replace with your frontend image
    container_name: frontend
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    image: oleksiipasichnyk/confl:hackaton-argo-2a77b51-20241118 # Replace with your backend image
    container_name: backend
    environment:
      MONGO_URI: "#####################" # Replace with your MongoDB URI
      SERVER_PORT: 5001
      JWT_SECRET: "sup per key 8426"
      MISTRAL_API: "https://api.mistral.ai"
      MISTRAL_TOKEN: "#####################" # Replace with your MongoDB URI
      UPLOAD_DIR: "/uploads"
      SERVER_IMAGE_STORE: "https://3dentai-nginx.labofdev.com/files"
    volumes:
      - uploads:/app/uploads  # Mount shared uploads directory
    networks:
      - app-network

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./nginx/ssl:/etc/letsencrypt  # Mount to store SSL certificates
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h; done'"
    depends_on:
      - nginx
    networks:
      - app-network

volumes:
  uploads:
    driver: local
    driver_opts:
      type: none
      device: "/app/uploads"  # Update with the path to your mounted hard drive
      o: bind

networks:
  app-network:
    driver: bridge
