version: '3.8'

services:

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"    # HTTP for initial Certbot validation
      - "443:443"  # HTTPS for secure access
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro  # Custom NGINX config
      - ./nginx/ssl:/etc/letsencrypt  # Mount for Let's Encrypt certificates
      - uploads:/usr/share/nginx/html/files  # Serve files from uploads directory
    depends_on:
      - frontend
      - backend
    networks:
      - app-network

  frontend:
    image: your-frontend-image:latest  # Replace with your frontend image
    container_name: frontend
    environment:
      - BACKEND_URL=http://backend:4000  # Backend service URL
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    image: your-backend-image:latest  # Replace with your backend image
    container_name: backend
    environment:
      - MONGO_URI=mongodb://external-mongo-db-url:27017/dbname  # Replace with your MongoDB URI
      - UPLOAD_DIR=/uploads
    volumes:
      - uploads:/uploads  # Mount shared uploads directory
    networks:
      - app-network

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./nginx/ssl:/etc/letsencrypt  # Mount to store SSL certificates
      - ./nginx/ssl-dhparams:/ssl-dhparams  # Custom Diffie-Hellman params for security
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h; done'"
    depends_on:
      - nginx
    networks:
      - app-network

volumes:
  uploads:

networks:
  app-network:
    driver: bridge
