pipeline {
    agent {
        kubernetes {
            yaml """
            apiVersion: v1
            kind: Pod
            spec:
              containers:
              - name: jnlp
                image: jenkins/inbound-agent:latest
                resources:
                  requests:
                    memory: "4Gi"
                    cpu: "2"
                  limits:
                    memory: "8Gi"
                    cpu: "4"
              - name: docker
                image: docker:20.10.8-dind
                securityContext:
                  privileged: true  # Required for Docker-in-Docker
                volumeMounts:
                - name: docker-graph-storage
                  mountPath: /var/lib/docker
              volumes:
              - name: docker-graph-storage
                emptyDir: {}
            """
        }
    }

    environment {
        DOCKER_HUB_TOKEN = credentials('dockerhub-token')
        DOCKER_IMAGE = 'oleksiipasichnyk/confl:hackaton-server'
        K8S_MANIFEST_PATH = 'server/kubernetes-configs/server-deployment-server.yaml'
        REPO_URL = 'git@github.com:Volodarskyi/3dentai.git'
        GIT_SSH_KEY = credentials('github-ssh-key')
        SERVER_DIR = 'server'
    }

    stages {
        stage('Build Docker Image') {
            steps {
                container('docker') {  // Use the docker container in the Kubernetes pod
                    script {
                        def commitHash = sh(script: "git rev-parse --short HEAD", returnStdout: true).trim()
                        def date = sh(script: "date +%Y%m%d", returnStdout: true).trim()
                        def imageTag = "${DOCKER_IMAGE}-${commitHash}-${date}"

                        // Docker build within the 'server' directory
                        sh """
                        docker build -t ${imageTag} .
                        """
                    }
                }
            }
        }

        stage('Push Docker Image to DockerHub') {
            steps {
                container('docker') {  // Use the docker container for pushing the image
                    script {
                        def commitHash = sh(script: "git rev-parse --short HEAD", returnStdout: true).trim()
                        def date = sh(script: "date +%Y%m%d", returnStdout: true).trim()
                        def imageTag = "${DOCKER_IMAGE}-${commitHash}-${date}"

                        // DockerHub login and push
                        sh """
                        echo ${DOCKER_HUB_TOKEN} | docker login -u your-dockerhub-username --password-stdin
                        docker push ${imageTag}
                        """
                    }
                }
            }
        }

        // Other stages...
    }
}
