apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  labels:
    argocd.argoproj.io/instance: root-app-of-apps
  name: backend-hackaton
  namespace: argocd
spec:
  destination:
    namespace:  backend-hackaton
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://github.com/Volodarskyi/3dentai
    targetRevision: develop
    path: infrastructure/kubernetes-configs/dev/argo-cd/client
  syncPolicy:
    automated:
      prune: false
      selfHeal: true