apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: nginx-files.paxel.ca
  namespace: hackaton-argo
spec:
  secretName: nginx-files.paxel.ca-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: nginx-files.paxel.ca
  dnsNames:
  - nginx-files.paxel.ca