apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: hackaton-server.paxel.ca
  namespace: hackaton-argo
spec:
  secretName: hackaton-server.paxel.ca-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: hackaton-server.paxel.ca
  dnsNames:
  - hackaton-server.paxel.ca